apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavorites-ingress-viewer
  labels:
    app: kavorites-ingress-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavorites-ingress-viewer
  template:
    metadata:
      labels:
        app: kavorites-ingress-viewer
    spec:
      serviceAccountName: kavorites-ingress-viewer
      containers:
      - name: ingress-viewer
        image: kavorites-ingress-viewer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kavorites-ingress-viewer
  labels:
    app: kavorites-ingress-viewer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: kavorites-ingress-viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kavorites-ingress-viewer
  labels:
    app: kavorites-ingress-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kavorites-ingress-viewer
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kavorites-ingress-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kavorites-ingress-viewer
subjects:
- kind: ServiceAccount
  name: kavorites-ingress-viewer
  namespace: default 